print(int(10.57))
print(int(True))
print(int(False))
print(int(10))
print(int(0.0))
#print(int("Ten"))

print("="*40)
print(float(10.57))
print(float(True))
print(float(False))
print(float(10))
print(float("10.0"))
#print(float("Ten"))

print("="*40)
print(str(10.57))
print(str(True))
print(str(False))
print(str(10))
print(str("10.0"))
print(str("Ten"))
print("="*40)

print(bool(10.57))
print(bool(True))
print(bool(False))
print(bool(0.0))
print(bool("10.0"))
print(bool("Ten"))
print(bool(-1))
print("="*40)

